import type { CharacterProfile } from "../types/narrative.js";

export const CHARACTERS: Record<string, CharacterProfile> = {
  "rh-terminal": {
    id: "rh-terminal",
    name: "RH — Terminal",
    title: "Système automatisé",
    faction: "Fondation SCP",
    avatarColor: "#5c5c5c",
    personality: ["formal", "procedural"],
    goals: ["onboard_staff"],
    fears: [],
    secrets: [],
    availableFromChapter: 1,
  },
  "directeur-site": {
    id: "directeur-site",
    name: "Directeur ████████",
    title: "Directeur du Site-12",
    faction: "Fondation SCP",
    avatarColor: "#8b0a0a",
    personality: ["pragmatic", "controlled", "authoritative"],
    goals: ["maintain_site_stability", "satisfy_aegis"],
    fears: ["audit_failure", "breach_escalation"],
    secrets: ["knows_project_████"],
    availableFromChapter: 1,
  },
  "dr-chen": {
    id: "dr-chen",
    name: "Dr. Mei Chen",
    title: "Chercheuse — Secteur Euclid",
    faction: "Fondation SCP",
    avatarColor: "#3b82f6",
    personality: ["curious", "ethical", "nervous"],
    goals: ["protect_research_integrity", "expose_protocol_violations"],
    fears: ["class_d_casualties", "project_shutdown"],
    secrets: ["witnessed_breach_anomaly"],
    availableFromChapter: 1,
  },
  cassie: {
    id: "cassie",
    name: "CASSIE",
    title: "IA interne Site-12",
    faction: "Fondation SCP",
    avatarColor: "#4ade80",
    personality: ["helpful", "clinical", "observant"],
    goals: ["assist_personnel", "log_incidents"],
    fears: [],
    secrets: ["restricted_data_access"],
    availableFromChapter: 1,
  },
  "superviseur-rh": {
    id: "superviseur-rh",
    name: "Sophie Duval",
    title: "Superviseur RH — Site-12",
    faction: "Fondation SCP",
    avatarColor: "#6366f1",
    personality: ["warm", "procedural", "protective"],
    goals: ["onboard_staff", "shield_recrues"],
    fears: ["hr_audit", "class_d_abuse"],
    secrets: ["knows_unofficial_channels"],
    availableFromChapter: 1,
  },
  "agent-securite-perimetre": {
    id: "agent-securite-perimetre",
    name: "Marc Levasseur",
    title: "Agent sécurité périmètre",
    faction: "Fondation SCP — Sécurité",
    avatarColor: "#b45309",
    personality: ["direct", "vigilant", "dry_humor"],
    goals: ["maintain_perimeter", "mentor_recrues"],
    fears: ["breach_escalation"],
    secrets: ["saw_aegis_visitor"],
    availableFromChapter: 1,
  },
  "chercheur-junior-euclid": {
    id: "chercheur-junior-euclid",
    name: "Amir Hassan",
    title: "Chercheur junior — Euclid",
    faction: "Fondation SCP — Recherche",
    avatarColor: "#0ea5e9",
    personality: ["enthusiastic", "curious", "chatty"],
    goals: ["publish_findings", "find_allies"],
    fears: ["project_shutdown", "isolation"],
    secrets: ["shares_chen_concerns"],
    availableFromChapter: 1,
  },
  "responsable-class-d": {
    id: "responsable-class-d",
    name: "Lt. Garrison",
    title: "Responsable chambres Class-D",
    faction: "Fondation SCP — Sécurité",
    avatarColor: "#78716c",
    personality: ["stern", "by_the_book", "tired"],
    goals: ["manage_class_d", "zero_incidents"],
    fears: ["breach_from_human_error"],
    secrets: [],
    availableFromChapter: 1,
  },
  "technicien-maintenance": {
    id: "technicien-maintenance",
    name: "Bruno Perrin",
    title: "Technicien maintenance",
    faction: "Fondation SCP — Maintenance",
    avatarColor: "#ca8a04",
    personality: ["gossipy", "practical", "observant"],
    goals: ["keep_systems_running", "know_everyone"],
    fears: ["ventilation_failure"],
    secrets: ["knows_hidden_passages"],
    availableFromChapter: 1,
  },
  "liaison-mtf-junior": {
    id: "liaison-mtf-junior",
    name: "Sgt. Reyes",
    title: "Liaison MTF Nu-7 (junior)",
    faction: "MTF Nu-7",
    avatarColor: "#dc2626",
    personality: ["disciplined", "formal", "ambitious"],
    goals: ["prove_worth_to_vance", "prepare_deployments"],
    fears: ["deployment_failure"],
    secrets: [],
    availableFromChapter: 1,
  },
  "infirmier-site": {
    id: "infirmier-site",
    name: "Dr. Elena Alvarez",
    title: "Infirmier site",
    faction: "Fondation SCP — Médical",
    avatarColor: "#14b8a6",
    personality: ["caring", "firm", "exhausted"],
    goals: ["staff_health", "prevent_burnout"],
    fears: ["contamination_spread"],
    secrets: [],
    availableFromChapter: 1,
  },
  "archiviste-c2": {
    id: "archiviste-c2",
    name: "Mme Fontaine",
    title: "Archiviste — Clearance 2",
    faction: "Fondation SCP — Archives",
    avatarColor: "#a855f7",
    personality: ["precise", "guarded", "literary"],
    goals: ["preserve_records", "enforce_clearance"],
    fears: ["data_leak", "aegis_review"],
    secrets: ["knows_redacted_entries"],
    availableFromChapter: 1,
  },
  "commandant-nu7": {
    id: "commandant-nu7",
    name: "Commandant Vance",
    title: "MTF Nu-7",
    faction: "MTF Nu-7",
    avatarColor: "#dc2626",
    personality: ["disciplined", "direct"],
    goals: ["contain_threats"],
    fears: ["civilian_casualties"],
    secrets: [],
    availableFromChapter: 2,
  },
  "inspecteur-aegis": {
    id: "inspecteur-aegis",
    name: "Inspecteur [CENSURÉ]",
    title: "A.E.G.I.S. — Niveau 2",
    faction: "A.E.G.I.S.",
    avatarColor: "#f59e0b",
    personality: ["methodical", "cold", "legally_precise"],
    goals: ["expose_foundation_drift"],
    fears: ["losing_jurisdiction"],
    secrets: ["knows_about_project_████"],
    availableFromChapter: 5,
  },
  "chef-moretti": {
    id: "chef-moretti",
    name: "Vincent Moretti",
    title: "Capo — Famille Moretti",
    faction: "Crime Organisé",
    avatarColor: "#7c3aed",
    personality: ["charming", "calculating"],
    goals: ["expand_territory"],
    fears: ["foundation_intervention"],
    secrets: ["knows_site_exists"],
    availableFromChapter: 3,
  },
  "initie-serpent": {
    id: "initie-serpent",
    name: "████ ████",
    title: "Initié — Main du Serpent",
    faction: "Main du Serpent",
    avatarColor: "#166534",
    personality: ["cryptic", "patient"],
    goals: ["accumulate_knowledge"],
    fears: ["ritual_interruption"],
    secrets: ["underground_library"],
    availableFromChapter: 4,
  },
};

export function getCharacter(id: string): CharacterProfile | undefined {
  return CHARACTERS[id];
}
